### ISSUE TITLE
Can't run demo.py

### ISSUE THREAD

**Issue by pgleeson** [amin-nejat/stat-atlas#1] opened 2021-12-17 17:29 UTC
@amin-nejat Testing out the repo, and I'm getting an error at https://github.com/amin-nejat/StatAtlas/blob/master/Atlas/Atlas.py#L63
```
  File "/Users/padraig/git/StatAtlas/Atlas/Atlas.py", line 68, in visualize
    atlas_color[:,3] = 0
IndexError: index 3 is out of bounds for axis 1 with size 3
```

I tried removing that and running and it works, but every time I get a scene with random orientation and different colors for the cells, e.g.

<img width="873" alt="Screenshot 2021-12-17 at 17 28 18" src="https://user-images.githubusercontent.com/1556687/146584362-ae5df3d7-4ae5-4b2a-a209-3defeb8ffb71.png">

**Comment by amin-nejat** [comment] 2021-12-17 18:58
Thanks for pointing this out. I noticed that I didn't push the latest changes to this Github repository. I made significant changes to the repo including bug fixes, better visualizations, and improved methods (just pushed the edits). 

You might not be able to run the current demo files because of two dependencies. Since the StatAtlas is part of a bigger project (which is a private repository) I'm happy to directly send you the dependencies (two python classes called Neuron and Image), or add you to the private repository. Please let me know what works best.

**Comment by amin-nejat** [comment] 2024-04-25 13:40
The new updates to the code should've fixed this issue. I'm closing since I didn't get a response and I'm assuming that the issue is resolved.

**Closed as completed** 2024-04-25 13:39 UTC
